### ISSUE TITLE
Request // Add option to insert specific add after x videos // Auto import videos to shedule

### ISSUE THREAD

**Issue by dfranje** [ffplayout/ffplayout#111]
It would be great if we could have an option to add a video add after X number of videos.
It would save time.

And also to implement auto playlist generation for x number of days ( the generator script is not working for me )

Thanks, Damir

**Comment by jb-alvarado** [comment]
Belongs this to the engine, or the frontend? 

Pull requests are always welcome.

**Comment by jb-alvarado** [comment]
Sorry @dfranje, I don't know if you are still interested in this feature. I never really liked the idea of implementing it because it is a very specific use case with not that much flexibility. But I also understand that it can be useful for some people, so I did some brainstorming. 

I could imagine implementing something more generic and flexible, which would help for your use case, but give more options on top. But my idea was more in the direction of an advanced folder mode rather than a playlist mode. Maybe I could add a second config file with a structure like this:

```YAML
{
    "repeat_daily": true, # plays for 24 hours and then starts from the beginning
    "fillers": "/tv-media/fillers", # use clips from this folder to fill the end
    "program": [
        {
            "shuffle": true,
            "repeat_every": "2h",
            "duration": "5m",
            "path": "/tv-media/ads"
        },
        {
            "shuffle": false,
            "repeat_every": "0",
            "duration": "4h",
            "path": "/tv-media/series"
        },
        {
            "shuffle": true,
            "repeat_every": "5h",
            "duration": "15m",
            "path": "/tv-media/music"
        }
    ]
}
```

As I said, this is just a brainstorming, so ideas and help are welcome. As I'm writing this, it occurs to me that it's also possible to generate a playlist from this.
