### ISSUE TITLE
Add trigger on video change

### ISSUE THREAD

**Issue by 0DUDDU** [ffplayout/ffplayout#276]
Hello,

I'm using ffplayout to stream to Twitch, I have made a script that call the API to get the current playing file and update the title on twitch but it run with a cron and sometine the title is not sync due to the length of video.
It would be cool to add an option to call a script on video change

Thanks 😄

**Comment by jb-alvarado** [comment]
Hello @0DUDDU,
I will think about it but at the moment I can not guarantee that I will integrate it. Some hooks on different events I could imagine, but running a script sound a bit to specific. I will also invest on how difficult it is, to create a script interface. 

But as a fast solution I have 3 options in mind:

1. You can write a script that makes a JSON RPC/or API call, reads beside the title the remaining time and sleep for that time until it makes the next call to get the next clip.
2. You write a script that read the playlist and calculate the current title.
3. You create a script that monitor the logging output and when a new clip comes in, you create your event.

If you need some help for that I can assist. With python you can realize this relatively easy and instead of a cron job you could create systemd service which keep the script running.

**Comment by 0DUDDU** [comment]
Thanks for your reply, a webhook or something like that would also fit.

I use nodejs for my script as I'm more familiar with javascript for basic scripting, it's already working in cron so i will made some change to run it as systemd service with sleep.

Btw, I'm using it inside k8s, if you want I can open a pull request with some documentation about creating a Docker/using k8s for ffplayout . I'm using [centos](https://hub.docker.com/_/centos) image as base image as it can run systemd in a container, that's why I needed the rpm.

**Comment by jb-alvarado** [comment]
Cool, I didn't know that they make it so easy to use systemd in Docker.

Yes a pull request is welcome, but please in the v0.17.0 branch.

**Comment by jb-alvarado** [comment]
Just a Note: The crate PyO3 can read python scripts at [runtime](https://docs.rs/pyo3/latest/pyo3/types/struct.PyModule.html#example-load-a-file-at-runtime-with-stdfsread_to_string), this could be a way for an interface. 

Maybe a predefined file like: **/usr/local/lib/ffplayout/ffmodule.py** and then certain predefined functions in it, which user can fill by them self, like:

```Python
def next_clip_hook(media_obj):
    """
    user can add his code, to do something with media_obj,
    for example calling request.post()
    """

    x = requests.post(url, json = media_obj)

    return x.text
```

**Comment by 0DUDDU** [comment]
Yes, that's could be good way for doing it

**Comment by alienmaster9** [comment]
@0DUDDU  have you implemented already. i want the exact thing if you have code please let me know

**Comment by alienmaster9** [comment]
i want to send current movie name on video playing how thats gona be possible and while movie is going to end i want to display timer that in how many seconds next movie play

**Comment by alienmaster9** [comment]
not just time need movie name displayed all the time how could i set that @jb-alvarado

**Comment by alienmaster9** [comment]
i want to display movie name on streaming output. target is movie channel and display movie names on stream output

**Comment by jb-alvarado** [comment]
So you want to overlay the filename? That can be done by config (text_from_filename):

```YAML
text:
    help_text: Overlay text in combination with libzmq for remote text manipulation.
        On windows fontfile path need to be like this 'C\:/WINDOWS/fonts/DejaVuSans.ttf'.
        'text_from_filename' activate the extraction from text of a filename. With 'style'
        you can define the drawtext parameters like position, color, etc. Post Text over
        API will override this. With 'regex' you can format file names, to get a title from it.
    add_text: true
    text_from_filename: true
    fontfile: "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
    style: "x=(w-tw)/2:y=(h-line_h)*0.9:fontsize=24:fontcolor=#ffffff:box=1:boxcolor=#000000:boxborderw=4"
    regex: ^.+[/\\](.*)(.mp4|.mkv)$
```
