### ISSUE TITLE
[Enhancement] acceleration on input

### ISSUE THREAD

**Issue by LuizStSantos** [ffplayout/ffplayout#558]
As discussed in #548 The possibility where we can define the input type and acceleration in ffmpeg without harming common users,
To be able to do this in our own settings, type of acceleration among other possibilities

**Comment by jb-alvarado** [comment]
Example ffmpeg command from @cooliobr:

```
ffmpeg -hide_banner -threads 4 -hwaccel cuvid -c:v h264_cuvid -fix_sub_duration -drop_second_field true \
-nostats -v level+error -stream_loop 6 \
-i /var/lib/ffplayout/media1G/hm/SPOT/HALLO_MOVIES_NEW.mp4 -t 60 -filter_complex \
[0:v:0]scale_npp=format=yuv420p,scale_npp=1280:720:interp_algo=super:force_original_aspect_ratio=decrease,hwdownload,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=black,setdar=16:9,setsar=1:1,hwupload[v];movie=/usr/share/ffplayout/HALLO_Movies_2.png[l0];[l0]format=rgba,colorchannelmixer=aa=0.7,scale=iw*0.4:-1,hwupload_cuda[l];[v][l]overlay_cuda=main_w-overlay_w-50:33,realtime=speed=1.0004316593661566[vout0];[0:a:0]anull[aout0] \
-map [vout0] -map [aout0] -c:v h264_nvenc -aspect 16:9 -r:v 30 -b:v 2200k -maxrate 2700k -bufsize 3100k \
-profile:v main -preset p4 -level 41 -delay 0 -ar 48000 -b:a 128k -c:a libfdk_aac -muxdelay 0 \
-colorspace:v bt709 -color_primaries:v bt709 -color_trc:v bt709 -color_range:v tv -f hls -hls_time 6 -hls_list_size 10 \
-g 60 -keyint_min 60 \
-hls_flags second_level_segment_index+append_list+omit_endlist+delete_segments+program_date_time \
-strftime 1 -hls_segment_filename /usr/share/ffplayout/public/live/ch3/stream-%v-%%04d.ts \
/usr/share/ffplayout/public/live/ch3/playlist.m3u8
```

Modified line: https://github.com/cooliobr/ffplayout2/commit/071bddf0b9e8ed91fa35dd5b75a91e8e12c2e16a

**Comment by jb-alvarado** [comment]
@cooliobr, can you give a correct updated ffmpeg command for ffmpeg 5+?.

And in you fork I saw also that some filters you command out, is there another way to keep them?

**Comment by cooliobr** [comment]
> @cooliobr, can you give a correct updated ffmpeg command for ffmpeg 5+?.
> 
> And in you fork I saw also that some filters you command out, is there another way to keep them?

I saw in your personal repository some modifications that you are making, you could keep it like this, if the operator changes the settings to advanced, he could manually edit "https://github.com/jb-alvarado/ffplayout/commit/5b68fc4fbc4f477e1c81688cdbfdc98bfce1623f"
The commands I use in ffmpeg today to take advantage of 100% of the GPU for everything I need, look like this ` ffmpeg -hide_banner -threads 4 -hwaccel cuvid -fix_sub_duration -drop_second_field true -nostats -v level+error -i /var/lib/ffplayout/tv-media/Ponto Cego/S01/Ponto Cego_S01E06_Ceder sua alma.mp4 -filter_complex [0:v:0]scale_npp=format=yuv420p,scale_npp=1280:720:interp_algo=super:force_original_aspect_ratio=decrease,hwdownload,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=black,setdar=16:9,setsar=1:1,hwupload[v];movie=/usr/share/ffplayout/HALLO_Plus.png[l0];[l0]format=rgba,colorchannelmixer=aa=0.7,scale=iw*0.6:-1,hwupload_cuda[l];[v][l]overlay_cuda=main_w-overlay_w-50:33,realtime=speed=1.0002263540752843[vout0];[0:a:0]anull,volume=5[aout0];[0:a:1]anull,volume=5[aout1] -map [vout0] -map [aout0] -map [aout1] -c:v h264_nvenc -aspect 16:9 -r:v 30 -b:v 3200k -maxrate 3700k -bufsize 3800k -profile:v main -preset p4 -level 41 -delay 0 -ar 48000 -b:a 128k -c:a libfdk_aac -map 0:s:0 -c:s webvtt -muxdelay 0 -metadata:s:a:1 language=Por -metadata:s:a:0 language=Eng -streamid 0:0x01E1 -streamid 1:0x01E2 -streamid 2:0x01E3 -colorspace:v bt709 -color_primaries:v bt709 -color_trc:v bt709 -color_range:v tv -f hls -hls_time 6 -hls_list_size 10 -g 60 -keyint_min 60 -hls_flags iframes_only+append_list+omit_endlist+delete_segments+program_date_time+split_by_time+append_list+round_durations -var_stream_map v:0,agroup:audio,s:0,sgroup:subtitle,default:yes,language:Por a:0,agroup:audio,language:Eng,default:yes a:1,language:Por,agroup:audio -hls_segment_filename /usr/share/ffplayout/public/live/ch1/stream-%v-%05d.ts /usr/share/ffplayout/public/live/ch1/stream_%v.m3u8`. 


By the way, if you want to make a button to enable and disable hardware acceleration I'm happy to help with the parameters, INTEL (SQV) and NVidia (CUVID)

**Comment by jb-alvarado** [comment]
Thanks @cooliobr for the suggestions!

My plan was not to implement anything in the frontend, nor any HW presets. I would leave the new config file as it is, with empty parameters and user can change as they want on terminal.

But some HW examples in the documentation would be nice! If you want to help, I'm happy!

**Comment by Nejooo** [comment]
Hello, @jb-alvarado it'd be great if you'd implement it as you proposed it, however I'd quite like it if you could see the params in the frontend if possible so if someone else were to create a new channel, they could just copy the existing configuration without having the knowledge of configuration file itself, thanks!

**Comment by cooliobr** [comment]
> Thanks @cooliobr for the suggestions!
> 
> My plan was not to implement anything in the frontend, nor any HW presets. I would leave the new config file as it is, with empty parameters and user can change as they want on terminal.
> 
> But some HW examples in the documentation would be nice! If you want to help, I'm happy!

I will use your config https://github.com/jb-alvarado/ffplayout/commit/5b68fc4fbc4f477e1c81688cdbfdc98bfce1623f as a parameter and will make comments for Nvidia and Intel.

**Comment by jb-alvarado** [comment]
That is great! I only made some changes to it.

**Comment by cooliobr** [comment]
> That is great! I only made some changes to it.

See if you can understand.
```
help: Changing these settings is for advanced users only! There will be no support or guarantee that it will be stable after changing it. It is for NVidia with cuda 12.2
decoder:
    input_options: -hwaccel_device 0 -hwaccel cuvid -hwaccel_output_format cuda
    output_options:
    filters:
        deinterlace: yadif_cuda=0:-1:0
        pad_scale_w: scale_npp={}:-1,
        pad_scale_h: scale=-1:{},
        pad_video: '{}pad={}:{}:(ow-iw)/2:(oh-ih)/2:color=black,setdar={}:{},setsar={}:{},hwupload'
        fps: fps={}
        scale: scale_npp=format=yuv420p,scale_npp={}:{}:interp_algo=super:force_original_aspect_ratio=decrease,hwdownload,
        set_dar: setdar={}
        fade_in: {}fade=in:st=0:d=0.5
        fade_out: {}fade=out:st={}:d=1.0
        overlay_logo_scale: ',scale=iw*{}:-1,hwupload_cuda'
        overlay_logo: null[v];movie={}:loop=0,setpts=N/(FRAME_RATE*TB),format=rgba,colorchannelmixer=aa={}{}[l];[v][l]overlay_cuda=main_w-overlay_w-{},realtime=speed=1.000225659584865
        overlay_logo_fade_in: ',fade=in:st=0:d=1.0:alpha=1'
        overlay_logo_fade_out: ',fade=out:st={}:d=1.0:alpha=1'
        tpad: tpad=stop_mode=add:stop_duration={}
        drawtext_from_file: drawtext=text='{}':{}{}
        drawtext_from_zmq: zmq=b=tcp\\\\://'{}',drawtext@dyntext={}
        apad: apad=whole_dur={}
        volume: volume={}
        split: split={}{}
encoder:
    input_options:
```

**Comment by jb-alvarado** [comment]
Looks good @cooliobr,
I command out all default filters, so you only have to uncommand a filter if you change it.

There is now a version in my dev repo that contains all the changes, would be nice if you guys could test it.

**Comment by LuizStSantos** [comment]
@cooliobr Could you make a new example to make the most of the video card using cuda 12.0?

**Comment by cooliobr** [comment]
I haven't tried the new version yet, but I believe I can do it in a week

**Comment by LuizStSantos** [comment]
> I haven't tried the new version yet, but I believe I can do it in a week

OK thank you

**Comment by cooliobr** [comment]
I tested every possible way to make it work with the advanced.yml version but I was unsuccessful, I'm going to make some changes to the ffplayout source and upload a specific version for nvidia to my repo

**Comment by LuizStSantos** [comment]
> I tested every possible way to make it work with the advanced.yml version but I was unsuccessful, I'm going to make some changes to the ffplayout source and upload a specific version for nvidia to my repo

OK, I had the same problem and I can't use it, so I asked for your help

**Comment by jb-alvarado** [comment]
I make some little changes and I had to introduce a braking change in the config, but now I get this advanced config to work:

```YAML
help: Changing these settings is for advanced users only! There will be no support or guarantee that it will be stable after changing them.
decoder:
    input_param: -hwaccel qsv -init_hw_device qsv=hw -filter_hw_device hw -hwaccel_output_format qsv -c:v hevc_qsv -load_plugin hevc_hw
    # output_param get also applied to ingest instance.
    output_param: -c:v mpeg2_qsv -g 1 -b:v 50000k -minrate 50000k -maxrate 50000k -bufsize 25000k -c:a s302m -strict -2 -sample_fmt s16 -ar 48000 -ac 2
    filters:
        deinterlace: deinterlace_qsv
        pad_scale_w: scale_qsv={}:-1,
        pad_scale_h: scale_qsv=-1:{},
        pad_video: 'null' # '{}pad=max(iw\\,ih*({0}/{1})):ow/({0}/{1}):(ow-iw)/2:(oh-ih)/2'
        fps: vpp_qsv=framerate=25
        scale: scale_qsv={}:{}
        set_dar: 'null' # setdar=dar={}
        fade_in: 'null' # '{}fade=in:st=0:d=0.5'
        fade_out: 'null' # '{}fade=out:st={}:d=1.0'
        overlay_logo_scale: ',scale_qsv={}'
        overlay_logo: null[v];movie={}:loop=0,setpts=N/(FRAME_RATE*TB),format=rgba,colorchannelmixer=aa={}{},hwupload=extra_hw_frames=64,format=qsv[l];[v][l]overlay_qsv={}:shortest=1
        overlay_logo_fade_in: 'null' # ',fade=in:st=0:d=1.0:alpha=1'
        overlay_logo_fade_out: 'null' # ',fade=out:st={}:d=1.0:alpha=1'
        tpad: 'null' # tpad=stop_mode=add:stop_duration={}
        drawtext_from_file: 'null' # drawtext=text='{}':{}{}
        drawtext_from_zmq: 'null' # zmq=b=tcp\\\\://'{}',drawtext@dyntext={}
        aevalsrc: # aevalsrc=0:channel_layout=stereo:duration={}:sample_rate=48000
        apad: # apad=whole_dur={}
        volume: # volume={}
        split: # split={}{}
encoder:
    input_param:
ingest:
    input_param:
```

I guess I get more filters to work, but with that settings I can reduce the CPU usage (with desktop output) from ~180% to 8%. I don't know how good this scales with multiple channels and how stable this is, but I found it impressive.

For this example I use the decoder `hevc_qsv` which only works with h265 encoded files...
