### ISSUE TITLE
Can we run multiple playlist in parallel with ffplayout

### ISSUE THREAD

**Issue by idealittechno-com** [ffplayout/ffplayout#566]
With FFPlayout, can we execute multiple playlist in parallel? I mean 3 instances running in background like these.
The Problem is, we cannot define name with command line argument and its managed by ffplayout.yml file which is one across whole ffplayout engine.

./ffplayout -l none -p ~/playlist1.json -o hls &
./ffplayout -l none -p ~/playlist2.json -o hls &
./ffplayout -l none -p ~/playlist3.json -o hls &

Please suggest whether its feasible with FFPlayout Engine. Thanks.

**Comment by jb-alvarado** [comment]
Yes, when you have enough system power you can run ffplayout multiple times. You only need for every instance a different config file. For example like:

```
./ffplayout -c ~/ffplayout1.yml  -l none -p ~/playlist1.json -o hls &
./ffplayout -c ~/ffplayout2.yml  -l none -p ~/playlist2.json -o hls &
./ffplayout -c ~/ffplayout3.yml  -l none -p ~/playlist3.json -o hls &
```

And of course you need different output paths in the settings.

When you are using the ffpapi/frontend you can manage your multiple channels there.

**Comment by idealittechno-com** [comment]
Thanks a lot jb-alvarado. This is how I was envisioning it although I'm getting this error if I ran the second command (first one is running fine) **[ERROR] Address 127.0.0.1:7070 already in use!**
I figured out that its a json rpc server running at 7070 port which restricting another instance to execute. I have tried marked it **enable=false** but it didnt seems working.

```
rpc_server:
  help_text: Run a JSON RPC server, for getting infos about current playing and for some control functions.
  enable: false
  address: 127.0.0.1:7070

```
Once I start the first command, I kill the job listened at 7070 and then I'm able to run two instance simultaneously. Hoping we can control it via .yml file.

**Comment by jb-alvarado** [comment]
>  I have tried marked it **enable=false** but it didnt seems working.

Yes that is a bit suboptimal: When text overlay (without text_from_filename) is on it also activate the RPC server. You have two options:

1. deactivate the text overlay 
2. change the RPC port

**Comment by idealittechno-com** [comment]
Thanks a lot !! I made these two changes in .yml file and now able to run two instances working fine. I'll work further to make RPC port unique per yml file. 

```
rpc_server:
  help_text: Run a JSON RPC server, for getting infos about current playing and for some control functions.
  enable: false
text:
  help_text: Overlay text in combination with libzmq for remote text manipulation. On windows fontfile path need to be like this 'C\:/WINDOWS/fonts/DejaVuSans.ttf'. 'text_from_filename' activate the ext>
  add_text: false

```
Thanks Again jb-alvarado.
