### ISSUE TITLE
Problem to change path of video

### ISSUE THREAD

**Issue by cooliobr** [ffplayout/ffplayout#701]
After installing and configuring the [alpha2](https://github.com/ffplayout/ffplayout/releases/tag/v0.24.0-alpha2) version, it is impossible to change the video path; it does not apply the settings.

**Comment by jb-alvarado** [comment]
Yes that is correct, this field will be hidden in future. It is only possible to set the storage on initialization. 

Changing can only be done by editing the db file.

**Comment by cooliobr** [comment]
you can explain how can change it ?
I have several channels, and each channel will use a different HDD. They are mounted in /var/lib/ffplayout/tv-media0, /var/lib/ffplayout/tv-media1, /var/lib/ffplayout/tv-media2

**Comment by jb-alvarado** [comment]
When you init the DB you should choice **no** for **shared storage**. For storage path you need to set: `/var/lib/ffplayout/tv-media`

And your mounts should be like:

```
/var/lib/ffplayout/tv-media/1
/var/lib/ffplayout/tv-media/2
/var/lib/ffplayout/tv-media/3
#...
```

**Comment by cooliobr** [comment]
ok, thanks

**Comment by cooliobr** [comment]
My Docker runs differently. I create the image as if it were a VM, then access it via SSH (ssh root@172.21.0.2 with pass Docker! ) and install with apt install or dnf-3 install. In both, I have systemd running. For Ubuntu, I use the image `cooliobr/ubuntu
````
##version: '3.7'
services:
    CLASSIC:
        devices:
            - /dev/nvidia-caps
            - /dev/nvidia0
            - /dev/nvidiactl
            - /dev/nvidia-modeset
            - /dev/nvidia-uvm
            - /dev/nvidia-uvm-tools
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:rw
            - /proc/sys/net:/net:rw
            - /logos:/logos:rw
            - /opt/playout_classic/conf:/etc/ffplayout:rw
            - /opt/playout_classic/db:/usr/share/ffplayout/db:rw
            - /disco/disco2/CLASSIC/:/var/lib/ffplayout/tv-media:rw
            - /disco/disco1/CLASSIC/5:/var/lib/ffplayout/tv-media/5:rw
            - /disco/disco3/7/:/var/lib/ffplayout/tv-media/7:rw
            - /dev/shm/playout_classic:/usr/share/ffplayout/public/live:rw
        ports:
            - '8087:8787'
            - '122:22'
            - '180:80'
            - '188:88'
            - '9998:9998'
            - '9998:9998/UDP'
            - '9988:9988'
            - '9988:9988/UDP'
            - '1935:1935'

        privileged: true
        restart: always
        #image: playout_nvidia
        #image: cooliobr/qsv_almalinux:8787
        #image: cooliobr/ubuntu:20.04
        image: cooliobr/qsv_cuda_almalinux:CLASSIC
        container_name: playout_classic
        deploy:
          resources:
            limits:
              cpus: '10.00'    
        #cpu_period: 100000
        #cpu_quota: 10000
        networks:
          network:
            ipv4_address: 172.21.0.2
        #deploy:
        #  resources:
        #    limits:
        #      cpus: '0.10'
        environment:
            - TZ=America/Sao_Paulo
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
        command:
            - '/usr/sbin/init'
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
          #volumes:
          #/media/Data/hallo:
          #storage_opt:
          #size: '2048G'              
````
